name: Build & Publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
  
jobs:
  build-and-publish:
    name: Build & Publish
    uses: elanco/solops-appexcellence-github-actions/.github/workflows/web-buildandpublish-web-api.yml@master
    with:
      default-bump-level: ''
    secrets:
      registry-read-token: ${{ secrets.REGISTRY_READ_TOKEN }}
      registry-write-token: ${{ secrets.REGISTRY_WRITE_TOKEN }}
      repository-read-token: ${{ secrets.REPOSITORY_READ_TOKEN }}
      repository-write-token: ${{ secrets.REPOSITORY_WRITE_TOKEN }}
