name: Terraform Provisioning

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target deployment environment (dev / prod)"
        required: true

jobs:
  terraform-provisioning:
    name: Terraform Provisioning
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: "Connect to Terraform Cloud"
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Variables File
        shell: bash
        run: cp infra/envs/${{ github.event.inputs.environment }}.terraform.tfvars infra/terraform.auto.tfvars

      - name: "Initialize Terraform"
        shell: bash
        run: terraform init
        working-directory: infra
    
      - name: "Terraform Apply"
        shell: bash
        run: terraform apply -auto-approve
