name: Continuous Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: src/web_sam
            image: web
          - path: src/api_sam
            image: api
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Declare variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
    
      - name: Push to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GOOGLE_ENCODED_CREDENTIALS }}
          registry: gcr.io
          project_id: web-pattern-prod-env-01
          image_name: ${{ matrix.image }}
          context: ${{ matrix.path }}
          image_tag: ${{ steps.vars.outputs.sha_short }}

      - name: "Connect to Terraform Cloud"
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Variables File
        shell: bash
        run: cp infra/envs/${{ github.event.inputs.environment }}.terraform.tfvars infra/terraform.auto.tfvars

      - name: "Initialize Terraform"
        shell: bash
        run: terraform init
        working-directory: infra
    
      - name: "Terraform Apply"
        shell: bash
        run: terraform apply -auto-approve
        working-directory: infra
